#!/usr/bin/env bash

pkill eww
pkill myshell
eww daemon

eww open bar
# eww open dock
eww open desktop1
eww open notifications_popup
# eww inspector

# start a bar for each monitor
monitors=$(hyprctl monitors -j | jq '.[] | .id')

for monitor in ${monitors}; do
    eww open desktop${monitor}
done


$HOME/.config/eww/scripts/myshell/./myshell --eww --file
